### ISSUE TITLE
prakata kepala sekolah

### ISSUE THREAD

**Issue by lianaangkasa** [dozymoe/smp-angkasa--ats#4]

**Comment by dozymoe** [comment]
Ada perubahan-perubahan:

1. Kalau edit laman-laman (web pages) ada tambahan field deskripsi (summary), ini yang bakal tampil di halaman muka bagian prakata.
2. Di menu utama sebelah kiri ada tambahan menu Konten-Konten Fitur (Front Contents).
3. Sementara ini belum bisa diatur urutannya, belum dikasih style.

**Comment by dozymoe** [comment]
Ini sudah selesai.
Prakata sudah bisa diatur urutannya.
